# Generated by Django 2.2.9 on 2020-01-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('blog', '0012_delete_skillsindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepageskillsitemicon',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='resumepageskillsitemicon',
            name='tag',
        ),
        migrations.DeleteModel(
            name='ResumePageSkillItem',
        ),
        migrations.DeleteModel(
            name='ResumePageSkillsItemIcon',
        ),
    ]
