# Generated by Django 2.2.9 on 2020-01-25 02:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0015_auto_20200125_0058'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResumePageSkill',
            new_name='Resume',
        ),
    ]
