# Generated by Django 2.2.9 on 2020-01-25 20:59

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20200125_0213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'this'},
        ),
        migrations.AddField(
            model_name='resume',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.ResumeCategory'),
        ),
    ]
