# Generated by Django 2.2.9 on 2020-01-26 02:54

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('blog', '0017_auto_20200125_2059'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeOther',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('text', wagtail.core.fields.RichTextField(blank=True)),
                ('categories', modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.ResumeCategory')),
            ],
            options={
                'verbose_name': 'this',
            },
            bases=('wagtailcore.page',),
        ),
    ]
