# Generated by Django 2.2.9 on 2020-01-26 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_resumeother'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumeother',
            options={},
        ),
        migrations.AlterField(
            model_name='resumeother',
            name='text',
            field=models.CharField(max_length=250),
        ),
    ]
