# Generated by Django 2.2.9 on 2020-02-15 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_resumedocument'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumepageitem',
            old_name='head',
            new_name='headA',
        ),
        migrations.AddField(
            model_name='resumepageitem',
            name='headB',
            field=models.CharField(default='n/a', max_length=250),
            preserve_default=False,
        ),
    ]
