# Generated by Django 2.2.9 on 2020-03-26 21:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200215_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeother',
            name='text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
