# Generated by Django 2.2.9 on 2020-03-26 21:21

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200326_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='hobbies',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='ri',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
