# Generated by Django 2.2.9 on 2020-02-10 04:49

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200126_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='sec1',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sec2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='sec3',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
